deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repo (for deploy.sh)
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: icpos-release
        path: .

    - name: Verify deploy script exists
      run: |
        test -f ./deploy/deploy.sh || (echo "ERROR: deploy/deploy.sh missing"; ls -la; exit 1)

    - name: Upload release to server (/tmp)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "release.tar.gz"
        target: "/tmp"

    - name: Upload deploy script to /tmp/deploy.sh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./deploy/deploy.sh"
        target: "/tmp"
        strip_components: 1
        overwrite: true

    - name: Debug list /tmp on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ls -la /tmp

    - name: Remote deploy (with fallback path)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          DEPLOY_SCRIPT="/tmp/deploy.sh"
          if [ ! -f "$DEPLOY_SCRIPT" ] && [ -f "/tmp/deploy/deploy.sh" ]; then
            DEPLOY_SCRIPT="/tmp/deploy/deploy.sh"
          fi
          if [ ! -f "$DEPLOY_SCRIPT" ]; then
            echo "deploy.sh not found in /tmp"; ls -la /tmp; exit 127
          fi
          sed -i 's/\r$//' "$DEPLOY_SCRIPT" || true
          bash "$DEPLOY_SCRIPT" \
            --base "${{ secrets.DEPLOY_BASE }}" \
            --tar "/tmp/release.tar.gz" \
            --php "/usr/bin/php" \
            --fpm "${{ secrets.PHP_FPM_SERVICE }}" \
            --nginx "${{ secrets.NGINX_SERVICE }}" \
            --release "${{ github.sha }}"
